[general]
working_directory="C:\\Users\\ethang"

[window]
padding.x=40
padding.y=20

[terminal]
shell.program="cmd.exe"
shell.args=["/k", "%CMDER_ROOT%/vendor/init.bat"]
osc52="CopyPaste"

[font]
normal.family="FiraCode Nerd Font"
size=10.0

[cursor]
style.shape="Block"
style.blinking="Always"

[mouse]
bindings=[
    {mouse="Right", action="Copy"},
]

[keyboard]
bindings=[
    {key="N", mods="Control|Shift", action="CreateNewWindow"},
]

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
